// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CourseInstructorDetailsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void courseInstructorDetails() {
    driver.get("https://udapps.nss.udel.edu/CoursesSearch/");
    driver.manage().window().setSize(new Dimension(892, 816));
    driver.findElement(By.id("term")).click();
    {
      WebElement dropdown = driver.findElement(By.id("term"));
      dropdown.findElement(By.xpath("//option[. = '2021 Fall (2218)']")).click();
    }
    driver.findElement(By.id("course_number")).click();
    driver.findElement(By.id("course_number")).sendKeys("CISC615");
    driver.findElement(By.cssSelector(".glyphicon-search")).click();
    driver.findElement(By.linkText("CISC615010")).click();
    js.executeScript("window.scrollTo(0,78.4000015258789)");
    {
      WebElement element = driver.findElement(By.linkText("Clause,James Alexander"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Clause,James Alexander")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("term")).click();
    driver.close();
  }
}
